In [ ]:
import xarray as xr
import pandas as pd
pd.set_option('display.max_rows', None)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount = True)

Mounted at /content/gdrive/

In [ ]:
ds = xr.open_dataset('/content/gdrive/MyDrive/Malaprabha/RF25_IMD0p252019_jas.nc')
df = ds.to_dataframe()
df.to_csv('data.csv')
df = pd.read_csv('data.csv')

In [ ]:
df['TIME'] = pd.to_datetime(df['TIME'], format='%Y-%m-%d')
df = df.sort_values(by = 'TIME')

In [ ]:
selected_df1 = df.loc[(df['LONGITUDE'] == 74) & (df['LATITUDE'] == 15.25) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df1 = selected_df1[~selected_df1['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df1

         LONGITUDE  LATITUDE       TIME    RAINFALL
1425537       74.0     15.25 2019-08-01   22.681793
1425538       74.0     15.25 2019-08-02    9.391395
1425539       74.0     15.25 2019-08-03   25.264044
1425540       74.0     15.25 2019-08-04   71.460754
1425541       74.0     15.25 2019-08-05  111.164440
1425542       74.0     15.25 2019-08-06  124.151764
1425543       74.0     15.25 2019-08-07   24.983541
1425544       74.0     15.25 2019-08-08   61.373775
1425545       74.0     15.25 2019-08-09   80.692960
1425546       74.0     15.25 2019-08-10   13.692200
1425547       74.0     15.25 2019-08-11    9.388779
1425548       74.0     15.25 2019-08-12   14.082118
1425549       74.0     15.25 2019-08-13   53.288742
1425550       74.0     15.25 2019-08-14   45.994606
1425551       74.0     15.25 2019-08-15  187.590350
1425552       74.0     15.25 2019-08-16   66.220860
1425553       74.0     15.25 2019-08-17   25.991838
1425554       74.0     15.25 2019-08-18   19.308548
1425555       74.0     15.25 2019-08-19   12.017462
1425556       74.0     15.25 2019-08-20   12.248503
1425557       74.0     15.25 2019-08-21    3.930506
1425558       74.0     15.25 2019-08-22    3.167150
1425559       74.0     15.25 2019-08-23   15.995807
1425560       74.0     15.25 2019-08-24   42.194576
1425561       74.0     15.25 2019-08-25   13.748949
1425562       74.0     15.25 2019-08-26    2.945241
1425563       74.0     15.25 2019-08-27    1.877493
1425564       74.0     15.25 2019-08-28    0.675137
1425565       74.0     15.25 2019-08-29    7.612161
1425566       74.0     15.25 2019-08-30   45.565350
1425567       74.0     15.25 2019-08-31   17.591078

In [ ]:
selected_df2 = df.loc[(df['LONGITUDE'] == 74.25) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df2 = selected_df2[~selected_df2['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df2

         LONGITUDE  LATITUDE       TIME    RAINFALL
1472987      74.25      15.5 2019-08-01   44.309880
1472988      74.25      15.5 2019-08-02   86.734720
1472989      74.25      15.5 2019-08-03  102.195755
1472990      74.25      15.5 2019-08-04  126.961000
1472991      74.25      15.5 2019-08-05  117.175900
1472992      74.25      15.5 2019-08-06  188.495360
1472993      74.25      15.5 2019-08-07  163.073400
1472994      74.25      15.5 2019-08-08  206.657350
1472995      74.25      15.5 2019-08-09  161.254170
1472996      74.25      15.5 2019-08-10  109.423010
1472997      74.25      15.5 2019-08-11   74.915830
1472998      74.25      15.5 2019-08-12   21.424604
1472999      74.25      15.5 2019-08-13   16.768173
1473000      74.25      15.5 2019-08-14   57.038345
1473001      74.25      15.5 2019-08-15   60.273212
1473002      74.25      15.5 2019-08-16   14.293013
1473003      74.25      15.5 2019-08-17    7.983575
1473004      74.25      15.5 2019-08-18    1.555532
1473005      74.25      15.5 2019-08-19    4.804791
1473006      74.25      15.5 2019-08-20    5.469265
1473007      74.25      15.5 2019-08-21    1.042199
1473008      74.25      15.5 2019-08-22    4.726168
1473009      74.25      15.5 2019-08-23   11.680622
1473010      74.25      15.5 2019-08-24   15.821044
1473011      74.25      15.5 2019-08-25   11.478155
1473012      74.25      15.5 2019-08-26    3.074760
1473013      74.25      15.5 2019-08-27    3.137595
1473014      74.25      15.5 2019-08-28    7.440012
1473015      74.25      15.5 2019-08-29   10.250791
1473016      74.25      15.5 2019-08-30   14.345266
1473017      74.25      15.5 2019-08-31   13.708822

In [ ]:
selected_df3 = df.loc[(df['LONGITUDE'] == 74.25) & (df['LATITUDE'] == 15.25) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df3 = selected_df3[~selected_df3['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df3

         LONGITUDE  LATITUDE       TIME    RAINFALL
1472622      74.25     15.25 2019-08-01   50.310047
1472623      74.25     15.25 2019-08-02   66.100914
1472624      74.25     15.25 2019-08-03   84.739770
1472625      74.25     15.25 2019-08-04   84.907500
1472626      74.25     15.25 2019-08-05  136.254440
1472627      74.25     15.25 2019-08-06  182.766170
1472628      74.25     15.25 2019-08-07  127.854110
1472629      74.25     15.25 2019-08-08  171.894240
1472630      74.25     15.25 2019-08-09  141.897610
1472631      74.25     15.25 2019-08-10   92.793880
1472632      74.25     15.25 2019-08-11   58.063236
1472633      74.25     15.25 2019-08-12   26.250504
1472634      74.25     15.25 2019-08-13   18.144743
1472635      74.25     15.25 2019-08-14   46.773970
1472636      74.25     15.25 2019-08-15  105.337610
1472637      74.25     15.25 2019-08-16   38.260387
1472638      74.25     15.25 2019-08-17   15.721527
1472639      74.25     15.25 2019-08-18   10.303849
1472640      74.25     15.25 2019-08-19    6.279941
1472641      74.25     15.25 2019-08-20    5.825600
1472642      74.25     15.25 2019-08-21    1.089434
1472643      74.25     15.25 2019-08-22    5.659139
1472644      74.25     15.25 2019-08-23   11.867087
1472645      74.25     15.25 2019-08-24   23.217682
1472646      74.25     15.25 2019-08-25   17.895334
1472647      74.25     15.25 2019-08-26    3.615385
1472648      74.25     15.25 2019-08-27    2.572682
1472649      74.25     15.25 2019-08-28    5.379593
1472650      74.25     15.25 2019-08-29   13.668775
1472651      74.25     15.25 2019-08-30   26.524385
1472652      74.25     15.25 2019-08-31   28.343327

In [ ]:
selected_df4 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df4 = selected_df4[~selected_df4['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df4

         LONGITUDE  LATITUDE       TIME    RAINFALL
1520072       74.5      15.5 2019-08-01   28.823076
1520073       74.5      15.5 2019-08-02   74.648040
1520074       74.5      15.5 2019-08-03  114.161450
1520075       74.5      15.5 2019-08-04   87.640500
1520076       74.5      15.5 2019-08-05   91.819650
1520077       74.5      15.5 2019-08-06  166.288150
1520078       74.5      15.5 2019-08-07  165.939000
1520079       74.5      15.5 2019-08-08  200.389830
1520080       74.5      15.5 2019-08-09  150.053400
1520081       74.5      15.5 2019-08-10   92.297530
1520082       74.5      15.5 2019-08-11   63.220590
1520083       74.5      15.5 2019-08-12   15.239024
1520084       74.5      15.5 2019-08-13    9.028052
1520085       74.5      15.5 2019-08-14   55.935665
1520086       74.5      15.5 2019-08-15   29.463495
1520087       74.5      15.5 2019-08-16    8.404264
1520088       74.5      15.5 2019-08-17    3.661467
1520089       74.5      15.5 2019-08-18    0.748001
1520090       74.5      15.5 2019-08-19    0.295876
1520091       74.5      15.5 2019-08-20    0.221801
1520092       74.5      15.5 2019-08-21    0.000000
1520093       74.5      15.5 2019-08-22    2.000753
1520094       74.5      15.5 2019-08-23    3.113939
1520095       74.5      15.5 2019-08-24    6.048833
1520096       74.5      15.5 2019-08-25    8.640527
1520097       74.5      15.5 2019-08-26    2.192355
1520098       74.5      15.5 2019-08-27    1.653305
1520099       74.5      15.5 2019-08-28    5.714606
1520100       74.5      15.5 2019-08-29    7.890469
1520101       74.5      15.5 2019-08-30    9.190267
1520102       74.5      15.5 2019-08-31    5.283891

In [ ]:
selected_df5 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 15.25) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df5 = selected_df5[~selected_df5['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df5

         LONGITUDE  LATITUDE       TIME    RAINFALL
1519707       74.5     15.25 2019-08-01   43.773144
1519708       74.5     15.25 2019-08-02   63.850372
1519709       74.5     15.25 2019-08-03   93.842440
1519710       74.5     15.25 2019-08-04   72.600600
1519711       74.5     15.25 2019-08-05   79.841060
1519712       74.5     15.25 2019-08-06  161.725720
1519713       74.5     15.25 2019-08-07  168.935460
1519714       74.5     15.25 2019-08-08  201.713440
1519715       74.5     15.25 2019-08-09  157.047600
1519716       74.5     15.25 2019-08-10   90.271500
1519717       74.5     15.25 2019-08-11   51.597630
1519718       74.5     15.25 2019-08-12   12.355905
1519719       74.5     15.25 2019-08-13   10.345475
1519720       74.5     15.25 2019-08-14   32.731224
1519721       74.5     15.25 2019-08-15   29.048296
1519722       74.5     15.25 2019-08-16    6.270887
1519723       74.5     15.25 2019-08-17    3.952291
1519724       74.5     15.25 2019-08-18    1.000000
1519725       74.5     15.25 2019-08-19    2.231244
1519726       74.5     15.25 2019-08-20    0.385969
1519727       74.5     15.25 2019-08-21    0.000000
1519728       74.5     15.25 2019-08-22    3.446034
1519729       74.5     15.25 2019-08-23    2.314980
1519730       74.5     15.25 2019-08-24    7.155803
1519731       74.5     15.25 2019-08-25   14.777746
1519732       74.5     15.25 2019-08-26    1.754666
1519733       74.5     15.25 2019-08-27    1.159055
1519734       74.5     15.25 2019-08-28    3.663972
1519735       74.5     15.25 2019-08-29   12.595344
1519736       74.5     15.25 2019-08-30    7.633749
1519737       74.5     15.25 2019-08-31   10.329623

In [ ]:
selected_df6 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df6 = selected_df6[~selected_df6['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df6

         LONGITUDE  LATITUDE       TIME    RAINFALL
1520072       74.5      15.5 2019-08-01   28.823076
1520073       74.5      15.5 2019-08-02   74.648040
1520074       74.5      15.5 2019-08-03  114.161450
1520075       74.5      15.5 2019-08-04   87.640500
1520076       74.5      15.5 2019-08-05   91.819650
1520077       74.5      15.5 2019-08-06  166.288150
1520078       74.5      15.5 2019-08-07  165.939000
1520079       74.5      15.5 2019-08-08  200.389830
1520080       74.5      15.5 2019-08-09  150.053400
1520081       74.5      15.5 2019-08-10   92.297530
1520082       74.5      15.5 2019-08-11   63.220590
1520083       74.5      15.5 2019-08-12   15.239024
1520084       74.5      15.5 2019-08-13    9.028052
1520085       74.5      15.5 2019-08-14   55.935665
1520086       74.5      15.5 2019-08-15   29.463495
1520087       74.5      15.5 2019-08-16    8.404264
1520088       74.5      15.5 2019-08-17    3.661467
1520089       74.5      15.5 2019-08-18    0.748001
1520090       74.5      15.5 2019-08-19    0.295876
1520091       74.5      15.5 2019-08-20    0.221801
1520092       74.5      15.5 2019-08-21    0.000000
1520093       74.5      15.5 2019-08-22    2.000753
1520094       74.5      15.5 2019-08-23    3.113939
1520095       74.5      15.5 2019-08-24    6.048833
1520096       74.5      15.5 2019-08-25    8.640527
1520097       74.5      15.5 2019-08-26    2.192355
1520098       74.5      15.5 2019-08-27    1.653305
1520099       74.5      15.5 2019-08-28    5.714606
1520100       74.5      15.5 2019-08-29    7.890469
1520101       74.5      15.5 2019-08-30    9.190267
1520102       74.5      15.5 2019-08-31    5.283891

In [ ]:
selected_df7 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 15.25) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df7 = selected_df7[~selected_df7['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df7

         LONGITUDE  LATITUDE       TIME    RAINFALL
1519707       74.5     15.25 2019-08-01   43.773144
1519708       74.5     15.25 2019-08-02   63.850372
1519709       74.5     15.25 2019-08-03   93.842440
1519710       74.5     15.25 2019-08-04   72.600600
1519711       74.5     15.25 2019-08-05   79.841060
1519712       74.5     15.25 2019-08-06  161.725720
1519713       74.5     15.25 2019-08-07  168.935460
1519714       74.5     15.25 2019-08-08  201.713440
1519715       74.5     15.25 2019-08-09  157.047600
1519716       74.5     15.25 2019-08-10   90.271500
1519717       74.5     15.25 2019-08-11   51.597630
1519718       74.5     15.25 2019-08-12   12.355905
1519719       74.5     15.25 2019-08-13   10.345475
1519720       74.5     15.25 2019-08-14   32.731224
1519721       74.5     15.25 2019-08-15   29.048296
1519722       74.5     15.25 2019-08-16    6.270887
1519723       74.5     15.25 2019-08-17    3.952291
1519724       74.5     15.25 2019-08-18    1.000000
1519725       74.5     15.25 2019-08-19    2.231244
1519726       74.5     15.25 2019-08-20    0.385969
1519727       74.5     15.25 2019-08-21    0.000000
1519728       74.5     15.25 2019-08-22    3.446034
1519729       74.5     15.25 2019-08-23    2.314980
1519730       74.5     15.25 2019-08-24    7.155803
1519731       74.5     15.25 2019-08-25   14.777746
1519732       74.5     15.25 2019-08-26    1.754666
1519733       74.5     15.25 2019-08-27    1.159055
1519734       74.5     15.25 2019-08-28    3.663972
1519735       74.5     15.25 2019-08-29   12.595344
1519736       74.5     15.25 2019-08-30    7.633749
1519737       74.5     15.25 2019-08-31   10.329623

In [ ]:
selected_df8 = df.loc[(df['LONGITUDE'] == 75) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df8 = selected_df8[~selected_df8['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df8

         LONGITUDE  LATITUDE       TIME    RAINFALL
1614242       75.0      15.5 2019-08-01    5.840276
1614243       75.0      15.5 2019-08-02   24.514490
1614244       75.0      15.5 2019-08-03    3.463954
1614245       75.0      15.5 2019-08-04   25.808949
1614246       75.0      15.5 2019-08-05   24.776790
1614247       75.0      15.5 2019-08-06   59.722340
1614248       75.0      15.5 2019-08-07   57.319637
1614249       75.0      15.5 2019-08-08  141.217320
1614250       75.0      15.5 2019-08-09   36.809216
1614251       75.0      15.5 2019-08-10   18.376450
1614252       75.0      15.5 2019-08-11   12.150774
1614253       75.0      15.5 2019-08-12    1.003157
1614254       75.0      15.5 2019-08-13    6.074211
1614255       75.0      15.5 2019-08-14    1.009084
1614256       75.0      15.5 2019-08-15    5.674701
1614257       75.0      15.5 2019-08-16    0.102875
1614258       75.0      15.5 2019-08-17    0.187495
1614259       75.0      15.5 2019-08-18    0.780111
1614260       75.0      15.5 2019-08-19    1.736923
1614261       75.0      15.5 2019-08-20    0.411499
1614262       75.0      15.5 2019-08-21    0.273394
1614263       75.0      15.5 2019-08-22    0.000000
1614264       75.0      15.5 2019-08-23    5.536539
1614265       75.0      15.5 2019-08-24    1.309057
1614266       75.0      15.5 2019-08-25    3.900760
1614267       75.0      15.5 2019-08-26    0.592344
1614268       75.0      15.5 2019-08-27    0.592344
1614269       75.0      15.5 2019-08-28    0.290370
1614270       75.0      15.5 2019-08-29    1.971852
1614271       75.0      15.5 2019-08-30    0.000000
1614272       75.0      15.5 2019-08-31    0.166689

In [ ]:
selected_df9 = df.loc[(df['LONGITUDE'] == 75) & (df['LATITUDE'] == 15.25) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df9 = selected_df9[~selected_df9['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df9

         LONGITUDE  LATITUDE       TIME   RAINFALL
1613877       75.0     15.25 2019-08-01   9.584166
1613878       75.0     15.25 2019-08-02  23.180250
1613879       75.0     15.25 2019-08-03   6.190819
1613880       75.0     15.25 2019-08-04  20.940063
1613881       75.0     15.25 2019-08-05  16.029180
1613882       75.0     15.25 2019-08-06  47.876995
1613883       75.0     15.25 2019-08-07  39.028740
1613884       75.0     15.25 2019-08-08  74.739700
1613885       75.0     15.25 2019-08-09  44.826862
1613886       75.0     15.25 2019-08-10  17.710485
1613887       75.0     15.25 2019-08-11  10.560844
1613888       75.0     15.25 2019-08-12   0.903474
1613889       75.0     15.25 2019-08-13   2.359997
1613890       75.0     15.25 2019-08-14   1.326906
1613891       75.0     15.25 2019-08-15   3.082200
1613892       75.0     15.25 2019-08-16   0.687139
1613893       75.0     15.25 2019-08-17   1.046655
1613894       75.0     15.25 2019-08-18   0.226692
1613895       75.0     15.25 2019-08-19   0.844353
1613896       75.0     15.25 2019-08-20   0.720471
1613897       75.0     15.25 2019-08-21   0.342540
1613898       75.0     15.25 2019-08-22   0.000000
1613899       75.0     15.25 2019-08-23   4.060171
1613900       75.0     15.25 2019-08-24   0.274272
1613901       75.0     15.25 2019-08-25   5.250127
1613902       75.0     15.25 2019-08-26   0.121880
1613903       75.0     15.25 2019-08-27   0.150699
1613904       75.0     15.25 2019-08-28   0.387011
1613905       75.0     15.25 2019-08-29   3.304452
1613906       75.0     15.25 2019-08-30   0.115275
1613907       75.0     15.25 2019-08-31   3.272169

In [ ]:
selected_df10 = df.loc[(df['LONGITUDE'] == 75.25) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df10 = selected_df10[~selected_df10['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df10

         LONGITUDE  LATITUDE       TIME   RAINFALL
1661327      75.25      15.5 2019-08-01   6.850673
1661328      75.25      15.5 2019-08-02   2.700840
1661329      75.25      15.5 2019-08-03   1.220921
1661330      75.25      15.5 2019-08-04  18.399035
1661331      75.25      15.5 2019-08-05   7.262888
1661332      75.25      15.5 2019-08-06  20.805172
1661333      75.25      15.5 2019-08-07  17.393305
1661334      75.25      15.5 2019-08-08  45.465878
1661335      75.25      15.5 2019-08-09   8.093689
1661336      75.25      15.5 2019-08-10   5.228382
1661337      75.25      15.5 2019-08-11   3.976384
1661338      75.25      15.5 2019-08-12   0.000000
1661339      75.25      15.5 2019-08-13   3.036205
1661340      75.25      15.5 2019-08-14   5.280736
1661341      75.25      15.5 2019-08-15   0.832409
1661342      75.25      15.5 2019-08-16   0.110463
1661343      75.25      15.5 2019-08-17   0.000000
1661344      75.25      15.5 2019-08-18   0.319483
1661345      75.25      15.5 2019-08-19  10.634078
1661346      75.25      15.5 2019-08-20   0.250091
1661347      75.25      15.5 2019-08-21   0.000000
1661348      75.25      15.5 2019-08-22   0.200606
1661349      75.25      15.5 2019-08-23  15.164208
1661350      75.25      15.5 2019-08-24   0.000000
1661351      75.25      15.5 2019-08-25   0.212888
1661352      75.25      15.5 2019-08-26   0.000000
1661353      75.25      15.5 2019-08-27   0.000000
1661354      75.25      15.5 2019-08-28   0.000000
1661355      75.25      15.5 2019-08-29   0.724683
1661356      75.25      15.5 2019-08-30   0.000000
1661357      75.25      15.5 2019-08-31   0.227958

In [ ]:
selected_df11 = df.loc[(df['LONGITUDE'] == 74) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df11 = selected_df11[~selected_df11['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df11

         LONGITUDE  LATITUDE       TIME    RAINFALL
1425902       74.0      15.5 2019-08-01   50.807793
1425903       74.0      15.5 2019-08-02   22.864624
1425904       74.0      15.5 2019-08-03   46.420610
1425905       74.0      15.5 2019-08-04  142.224560
1425906       74.0      15.5 2019-08-05  132.391000
1425907       74.0      15.5 2019-08-06  229.916870
1425908       74.0      15.5 2019-08-07   98.240845
1425909       74.0      15.5 2019-08-08  101.118210
1425910       74.0      15.5 2019-08-09  116.612290
1425911       74.0      15.5 2019-08-10   52.041634
1425912       74.0      15.5 2019-08-11   54.579890
1425913       74.0      15.5 2019-08-12   27.713764
1425914       74.0      15.5 2019-08-13   26.708260
1425915       74.0      15.5 2019-08-14   29.170092
1425916       74.0      15.5 2019-08-15  203.713100
1425917       74.0      15.5 2019-08-16   25.102888
1425918       74.0      15.5 2019-08-17   15.204048
1425919       74.0      15.5 2019-08-18    6.692230
1425920       74.0      15.5 2019-08-19    9.218102
1425921       74.0      15.5 2019-08-20   17.631899
1425922       74.0      15.5 2019-08-21    3.943596
1425923       74.0      15.5 2019-08-22    3.143073
1425924       74.0      15.5 2019-08-23   34.107746
1425925       74.0      15.5 2019-08-24   36.342080
1425926       74.0      15.5 2019-08-25    9.579317
1425927       74.0      15.5 2019-08-26    1.459435
1425928       74.0      15.5 2019-08-27    5.851656
1425929       74.0      15.5 2019-08-28   16.127262
1425930       74.0      15.5 2019-08-29   10.256283
1425931       74.0      15.5 2019-08-30   22.538805
1425932       74.0      15.5 2019-08-31   32.324350

In [ ]:
selected_df12 = df.loc[(df['LONGITUDE'] == 74.25) & (df['LATITUDE'] == 16) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df12 = selected_df12[~selected_df12['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df12

         LONGITUDE  LATITUDE       TIME    RAINFALL
1473717      74.25      16.0 2019-08-01   25.546238
1473718      74.25      16.0 2019-08-02   37.643420
1473719      74.25      16.0 2019-08-03   87.628200
1473720      74.25      16.0 2019-08-04   93.699646
1473721      74.25      16.0 2019-08-05   88.632920
1473722      74.25      16.0 2019-08-06  164.674960
1473723      74.25      16.0 2019-08-07  161.017070
1473724      74.25      16.0 2019-08-08  151.483730
1473725      74.25      16.0 2019-08-09  106.132150
1473726      74.25      16.0 2019-08-10  125.636510
1473727      74.25      16.0 2019-08-11   63.368740
1473728      74.25      16.0 2019-08-12   18.943975
1473729      74.25      16.0 2019-08-13    9.335587
1473730      74.25      16.0 2019-08-14    5.228314
1473731      74.25      16.0 2019-08-15   15.221355
1473732      74.25      16.0 2019-08-16    9.961703
1473733      74.25      16.0 2019-08-17    3.307849
1473734      74.25      16.0 2019-08-18    1.722686
1473735      74.25      16.0 2019-08-19    1.047492
1473736      74.25      16.0 2019-08-20    3.761505
1473737      74.25      16.0 2019-08-21    0.000000
1473738      74.25      16.0 2019-08-22    0.282877
1473739      74.25      16.0 2019-08-23    2.750692
1473740      74.25      16.0 2019-08-24   11.669145
1473741      74.25      16.0 2019-08-25    1.288786
1473742      74.25      16.0 2019-08-26    2.564073
1473743      74.25      16.0 2019-08-27    0.282877
1473744      74.25      16.0 2019-08-28    4.176971
1473745      74.25      16.0 2019-08-29    5.096462
1473746      74.25      16.0 2019-08-30    2.084989
1473747      74.25      16.0 2019-08-31    3.268922

In [ ]:
selected_df13 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df13 = selected_df13[~selected_df13['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df13

         LONGITUDE  LATITUDE       TIME    RAINFALL
1520072       74.5      15.5 2019-08-01   28.823076
1520073       74.5      15.5 2019-08-02   74.648040
1520074       74.5      15.5 2019-08-03  114.161450
1520075       74.5      15.5 2019-08-04   87.640500
1520076       74.5      15.5 2019-08-05   91.819650
1520077       74.5      15.5 2019-08-06  166.288150
1520078       74.5      15.5 2019-08-07  165.939000
1520079       74.5      15.5 2019-08-08  200.389830
1520080       74.5      15.5 2019-08-09  150.053400
1520081       74.5      15.5 2019-08-10   92.297530
1520082       74.5      15.5 2019-08-11   63.220590
1520083       74.5      15.5 2019-08-12   15.239024
1520084       74.5      15.5 2019-08-13    9.028052
1520085       74.5      15.5 2019-08-14   55.935665
1520086       74.5      15.5 2019-08-15   29.463495
1520087       74.5      15.5 2019-08-16    8.404264
1520088       74.5      15.5 2019-08-17    3.661467
1520089       74.5      15.5 2019-08-18    0.748001
1520090       74.5      15.5 2019-08-19    0.295876
1520091       74.5      15.5 2019-08-20    0.221801
1520092       74.5      15.5 2019-08-21    0.000000
1520093       74.5      15.5 2019-08-22    2.000753
1520094       74.5      15.5 2019-08-23    3.113939
1520095       74.5      15.5 2019-08-24    6.048833
1520096       74.5      15.5 2019-08-25    8.640527
1520097       74.5      15.5 2019-08-26    2.192355
1520098       74.5      15.5 2019-08-27    1.653305
1520099       74.5      15.5 2019-08-28    5.714606
1520100       74.5      15.5 2019-08-29    7.890469
1520101       74.5      15.5 2019-08-30    9.190267
1520102       74.5      15.5 2019-08-31    5.283891

In [ ]:
selected_df14 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 16) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df14 = selected_df14[~selected_df14['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df14

         LONGITUDE  LATITUDE       TIME    RAINFALL
1520802       74.5      16.0 2019-08-01    7.296167
1520803       74.5      16.0 2019-08-02   13.812697
1520804       74.5      16.0 2019-08-03   22.294876
1520805       74.5      16.0 2019-08-04   39.653442
1520806       74.5      16.0 2019-08-05   23.616583
1520807       74.5      16.0 2019-08-06   96.786150
1520808       74.5      16.0 2019-08-07  104.368930
1520809       74.5      16.0 2019-08-08  117.870735
1520810       74.5      16.0 2019-08-09   45.822150
1520811       74.5      16.0 2019-08-10   67.419120
1520812       74.5      16.0 2019-08-11   11.527362
1520813       74.5      16.0 2019-08-12    3.364997
1520814       74.5      16.0 2019-08-13    2.418733
1520815       74.5      16.0 2019-08-14    0.857825
1520816       74.5      16.0 2019-08-15    1.905248
1520817       74.5      16.0 2019-08-16    2.350670
1520818       74.5      16.0 2019-08-17    0.000000
1520819       74.5      16.0 2019-08-18    1.075663
1520820       74.5      16.0 2019-08-19    1.082963
1520821       74.5      16.0 2019-08-20    0.238449
1520822       74.5      16.0 2019-08-21    0.000000
1520823       74.5      16.0 2019-08-22    0.524267
1520824       74.5      16.0 2019-08-23    8.024052
1520825       74.5      16.0 2019-08-24    1.820301
1520826       74.5      16.0 2019-08-25    0.131067
1520827       74.5      16.0 2019-08-26    0.000000
1520828       74.5      16.0 2019-08-27    0.131067
1520829       74.5      16.0 2019-08-28    1.218604
1520830       74.5      16.0 2019-08-29    1.119958
1520831       74.5      16.0 2019-08-30    0.000000
1520832       74.5      16.0 2019-08-31    0.131067

In [ ]:
selected_df15 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df15 = selected_df15[~selected_df15['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df15

         LONGITUDE  LATITUDE       TIME    RAINFALL
1520072       74.5      15.5 2019-08-01   28.823076
1520073       74.5      15.5 2019-08-02   74.648040
1520074       74.5      15.5 2019-08-03  114.161450
1520075       74.5      15.5 2019-08-04   87.640500
1520076       74.5      15.5 2019-08-05   91.819650
1520077       74.5      15.5 2019-08-06  166.288150
1520078       74.5      15.5 2019-08-07  165.939000
1520079       74.5      15.5 2019-08-08  200.389830
1520080       74.5      15.5 2019-08-09  150.053400
1520081       74.5      15.5 2019-08-10   92.297530
1520082       74.5      15.5 2019-08-11   63.220590
1520083       74.5      15.5 2019-08-12   15.239024
1520084       74.5      15.5 2019-08-13    9.028052
1520085       74.5      15.5 2019-08-14   55.935665
1520086       74.5      15.5 2019-08-15   29.463495
1520087       74.5      15.5 2019-08-16    8.404264
1520088       74.5      15.5 2019-08-17    3.661467
1520089       74.5      15.5 2019-08-18    0.748001
1520090       74.5      15.5 2019-08-19    0.295876
1520091       74.5      15.5 2019-08-20    0.221801
1520092       74.5      15.5 2019-08-21    0.000000
1520093       74.5      15.5 2019-08-22    2.000753
1520094       74.5      15.5 2019-08-23    3.113939
1520095       74.5      15.5 2019-08-24    6.048833
1520096       74.5      15.5 2019-08-25    8.640527
1520097       74.5      15.5 2019-08-26    2.192355
1520098       74.5      15.5 2019-08-27    1.653305
1520099       74.5      15.5 2019-08-28    5.714606
1520100       74.5      15.5 2019-08-29    7.890469
1520101       74.5      15.5 2019-08-30    9.190267
1520102       74.5      15.5 2019-08-31    5.283891

In [ ]:
selected_df16 = df.loc[(df['LONGITUDE'] == 74.5) & (df['LATITUDE'] == 16) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df16 = selected_df16[~selected_df16['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df16

         LONGITUDE  LATITUDE       TIME    RAINFALL
1520802       74.5      16.0 2019-08-01    7.296167
1520803       74.5      16.0 2019-08-02   13.812697
1520804       74.5      16.0 2019-08-03   22.294876
1520805       74.5      16.0 2019-08-04   39.653442
1520806       74.5      16.0 2019-08-05   23.616583
1520807       74.5      16.0 2019-08-06   96.786150
1520808       74.5      16.0 2019-08-07  104.368930
1520809       74.5      16.0 2019-08-08  117.870735
1520810       74.5      16.0 2019-08-09   45.822150
1520811       74.5      16.0 2019-08-10   67.419120
1520812       74.5      16.0 2019-08-11   11.527362
1520813       74.5      16.0 2019-08-12    3.364997
1520814       74.5      16.0 2019-08-13    2.418733
1520815       74.5      16.0 2019-08-14    0.857825
1520816       74.5      16.0 2019-08-15    1.905248
1520817       74.5      16.0 2019-08-16    2.350670
1520818       74.5      16.0 2019-08-17    0.000000
1520819       74.5      16.0 2019-08-18    1.075663
1520820       74.5      16.0 2019-08-19    1.082963
1520821       74.5      16.0 2019-08-20    0.238449
1520822       74.5      16.0 2019-08-21    0.000000
1520823       74.5      16.0 2019-08-22    0.524267
1520824       74.5      16.0 2019-08-23    8.024052
1520825       74.5      16.0 2019-08-24    1.820301
1520826       74.5      16.0 2019-08-25    0.131067
1520827       74.5      16.0 2019-08-26    0.000000
1520828       74.5      16.0 2019-08-27    0.131067
1520829       74.5      16.0 2019-08-28    1.218604
1520830       74.5      16.0 2019-08-29    1.119958
1520831       74.5      16.0 2019-08-30    0.000000
1520832       74.5      16.0 2019-08-31    0.131067

In [ ]:
selected_df17 = df.loc[(df['LONGITUDE'] == 75) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df17 = selected_df17[~selected_df17['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df17

         LONGITUDE  LATITUDE       TIME    RAINFALL
1614242       75.0      15.5 2019-08-01    5.840276
1614243       75.0      15.5 2019-08-02   24.514490
1614244       75.0      15.5 2019-08-03    3.463954
1614245       75.0      15.5 2019-08-04   25.808949
1614246       75.0      15.5 2019-08-05   24.776790
1614247       75.0      15.5 2019-08-06   59.722340
1614248       75.0      15.5 2019-08-07   57.319637
1614249       75.0      15.5 2019-08-08  141.217320
1614250       75.0      15.5 2019-08-09   36.809216
1614251       75.0      15.5 2019-08-10   18.376450
1614252       75.0      15.5 2019-08-11   12.150774
1614253       75.0      15.5 2019-08-12    1.003157
1614254       75.0      15.5 2019-08-13    6.074211
1614255       75.0      15.5 2019-08-14    1.009084
1614256       75.0      15.5 2019-08-15    5.674701
1614257       75.0      15.5 2019-08-16    0.102875
1614258       75.0      15.5 2019-08-17    0.187495
1614259       75.0      15.5 2019-08-18    0.780111
1614260       75.0      15.5 2019-08-19    1.736923
1614261       75.0      15.5 2019-08-20    0.411499
1614262       75.0      15.5 2019-08-21    0.273394
1614263       75.0      15.5 2019-08-22    0.000000
1614264       75.0      15.5 2019-08-23    5.536539
1614265       75.0      15.5 2019-08-24    1.309057
1614266       75.0      15.5 2019-08-25    3.900760
1614267       75.0      15.5 2019-08-26    0.592344
1614268       75.0      15.5 2019-08-27    0.592344
1614269       75.0      15.5 2019-08-28    0.290370
1614270       75.0      15.5 2019-08-29    1.971852
1614271       75.0      15.5 2019-08-30    0.000000
1614272       75.0      15.5 2019-08-31    0.166689

In [ ]:
selected_df18 = df.loc[(df['LONGITUDE'] == 75) & (df['LATITUDE'] == 16) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df18 = selected_df18[~selected_df18['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df18

         LONGITUDE  LATITUDE       TIME   RAINFALL
1614972       75.0      16.0 2019-08-01   1.202122
1614973       75.0      16.0 2019-08-02   2.861899
1614974       75.0      16.0 2019-08-03   1.486676
1614975       75.0      16.0 2019-08-04  26.163734
1614976       75.0      16.0 2019-08-05   4.333377
1614977       75.0      16.0 2019-08-06  30.309256
1614978       75.0      16.0 2019-08-07  16.001715
1614979       75.0      16.0 2019-08-08  36.480843
1614980       75.0      16.0 2019-08-09   7.967836
1614981       75.0      16.0 2019-08-10   6.919601
1614982       75.0      16.0 2019-08-11   2.256072
1614983       75.0      16.0 2019-08-12   0.145288
1614984       75.0      16.0 2019-08-13   3.708299
1614985       75.0      16.0 2019-08-14   0.366540
1614986       75.0      16.0 2019-08-15   5.468181
1614987       75.0      16.0 2019-08-16   4.764035
1614988       75.0      16.0 2019-08-17   0.000000
1614989       75.0      16.0 2019-08-18   0.603221
1614990       75.0      16.0 2019-08-19   2.532401
1614991       75.0      16.0 2019-08-20   0.000000
1614992       75.0      16.0 2019-08-21   2.189539
1614993       75.0      16.0 2019-08-22   0.000000
1614994       75.0      16.0 2019-08-23   0.177229
1614995       75.0      16.0 2019-08-24   0.000000
1614996       75.0      16.0 2019-08-25   1.419547
1614997       75.0      16.0 2019-08-26   0.000000
1614998       75.0      16.0 2019-08-27   0.000000
1614999       75.0      16.0 2019-08-28   0.823298
1615000       75.0      16.0 2019-08-29   0.569161
1615001       75.0      16.0 2019-08-30   0.747451
1615002       75.0      16.0 2019-08-31   0.000000

In [ ]:
selected_df19 = df.loc[(df['LONGITUDE'] == 75) & (df['LATITUDE'] == 15.5) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df19 = selected_df19[~selected_df19['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df19

         LONGITUDE  LATITUDE       TIME    RAINFALL
1614242       75.0      15.5 2019-08-01    5.840276
1614243       75.0      15.5 2019-08-02   24.514490
1614244       75.0      15.5 2019-08-03    3.463954
1614245       75.0      15.5 2019-08-04   25.808949
1614246       75.0      15.5 2019-08-05   24.776790
1614247       75.0      15.5 2019-08-06   59.722340
1614248       75.0      15.5 2019-08-07   57.319637
1614249       75.0      15.5 2019-08-08  141.217320
1614250       75.0      15.5 2019-08-09   36.809216
1614251       75.0      15.5 2019-08-10   18.376450
1614252       75.0      15.5 2019-08-11   12.150774
1614253       75.0      15.5 2019-08-12    1.003157
1614254       75.0      15.5 2019-08-13    6.074211
1614255       75.0      15.5 2019-08-14    1.009084
1614256       75.0      15.5 2019-08-15    5.674701
1614257       75.0      15.5 2019-08-16    0.102875
1614258       75.0      15.5 2019-08-17    0.187495
1614259       75.0      15.5 2019-08-18    0.780111
1614260       75.0      15.5 2019-08-19    1.736923
1614261       75.0      15.5 2019-08-20    0.411499
1614262       75.0      15.5 2019-08-21    0.273394
1614263       75.0      15.5 2019-08-22    0.000000
1614264       75.0      15.5 2019-08-23    5.536539
1614265       75.0      15.5 2019-08-24    1.309057
1614266       75.0      15.5 2019-08-25    3.900760
1614267       75.0      15.5 2019-08-26    0.592344
1614268       75.0      15.5 2019-08-27    0.592344
1614269       75.0      15.5 2019-08-28    0.290370
1614270       75.0      15.5 2019-08-29    1.971852
1614271       75.0      15.5 2019-08-30    0.000000
1614272       75.0      15.5 2019-08-31    0.166689

In [ ]:
selected_df20 = df.loc[(df['LONGITUDE'] == 75.25) & (df['LATITUDE'] == 16) & (df['TIME'] >= pd.Timestamp(2019, 8, 1)) & (df['TIME'] <= pd.Timestamp(2019, 8, 31))]
selected_df20 = selected_df20[~selected_df20['RAINFALL'].isna()]
# selected_df = df.loc[(df['LONGITUDE'] == 73.25) & (df['LATITUDE'] == 36.25) & (df['TIME'] == pd.Timestamp(2019, 2, 1))]
# selected_df = df.loc[(df['LONGITUDE'] == 70.00) & (df['LATITUDE'] == 16.5)]
# selected_df = df['TIME'] == pd.Timestamp(2019, 4, 16)
selected_df20

         LONGITUDE  LATITUDE       TIME   RAINFALL
1662057      75.25      16.0 2019-08-01   0.603390
1662058      75.25      16.0 2019-08-02   2.233006
1662059      75.25      16.0 2019-08-03   0.995168
1662060      75.25      16.0 2019-08-04   9.588338
1662061      75.25      16.0 2019-08-05   2.440426
1662062      75.25      16.0 2019-08-06  21.503847
1662063      75.25      16.0 2019-08-07   7.106207
1662064      75.25      16.0 2019-08-08  18.044147
1662065      75.25      16.0 2019-08-09   2.129295
1662066      75.25      16.0 2019-08-10   1.371383
1662067      75.25      16.0 2019-08-11   2.988055
1662068      75.25      16.0 2019-08-12   0.000000
1662069      75.25      16.0 2019-08-13   3.823403
1662070      75.25      16.0 2019-08-14   0.422226
1662071      75.25      16.0 2019-08-15   6.190674
1662072      75.25      16.0 2019-08-16   3.954279
1662073      75.25      16.0 2019-08-17   0.000000
1662074      75.25      16.0 2019-08-18   0.792970
1662075      75.25      16.0 2019-08-19   1.838140
1662076      75.25      16.0 2019-08-20   0.000000
1662077      75.25      16.0 2019-08-21   0.000000
1662078      75.25      16.0 2019-08-22   0.000000
1662079      75.25      16.0 2019-08-23   0.173991
1662080      75.25      16.0 2019-08-24   0.296085
1662081      75.25      16.0 2019-08-25   2.111130
1662082      75.25      16.0 2019-08-26   0.000000
1662083      75.25      16.0 2019-08-27   0.000000
1662084      75.25      16.0 2019-08-28   0.000000
1662085      75.25      16.0 2019-08-29   0.543919
1662086      75.25      16.0 2019-08-30   0.000000
1662087      75.25      16.0 2019-08-31   0.525695